// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwiro_mCrXU1VKaDJx6laxhnsLDwbZjb4',
    appId: '1:52636595740:web:7e0a30a62704f59ce8d1d9',
    messagingSenderId: '52636595740',
    projectId: 'budgetapp2-d543c',
    authDomain: 'budgetapp2-d543c.firebaseapp.com',
    storageBucket: 'budgetapp2-d543c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpNt2XBIGse5DsP9EHd1UX091qLUI7bCc',
    appId: '1:52636595740:android:36b8784ce1b7ef35e8d1d9',
    messagingSenderId: '52636595740',
    projectId: 'budgetapp2-d543c',
    storageBucket: 'budgetapp2-d543c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwc2vWlUD74YB1VikNaXgxm4SjvI3bf2k',
    appId: '1:52636595740:ios:8ffedeb924eb24c2e8d1d9',
    messagingSenderId: '52636595740',
    projectId: 'budgetapp2-d543c',
    storageBucket: 'budgetapp2-d543c.firebasestorage.app',
    androidClientId: '52636595740-1oa8dsviruid8srjdnv8fmvi5spichgd.apps.googleusercontent.com',
    iosClientId: '52636595740-rtc5fd600mfljd72kql79bgncgl8e1on.apps.googleusercontent.com',
    iosBundleId: 'com.codingliquids.budgetAppCompleteProject',
  );

}